apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
  type: NodePort      # Exposes service on <NodeIP>:<NodePort>
