apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007   # you can pick any free port between 30000-32767
  type: NodePort
